name: Build (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -G "Ninja Multi-Config"
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Run Tests
        run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
        working-directory: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vctts-windows
          path: build/${{ env.BUILD_TYPE }}/vctts.exe

      - name: Create Release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: build/${{ env.BUILD_TYPE }}/vctts.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
